WebMvcPlusJqueryDragDropTableRows/Models/ErrorViewModel.cs
using System;

namespace WebMvcPlusJqueryDragDropTableRows.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebMvcPlusJqueryDragDropTableRows/Models/MvcDragDropDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMvcPlusJqueryDragDropTableRows.Models
{
    public class MvcDragDropDbContext : DbContext
    {

        public MvcDragDropDbContext()
        {
        }

        public MvcDragDropDbContext(DbContextOptions<MvcDragDropDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbMvcDragDropTableRows> tbMvcDragDropTableRows { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }
    }
}

WebMvcPlusJqueryDragDropTableRows/Models/tbMvcDragDropTableRows.cs
using System.ComponentModel.DataAnnotations;

namespace WebMvcPlusJqueryDragDropTableRows.Models
{
    public partial  class tbMvcDragDropTableRows
    {
        [Key]
      public int    id { get; set; }
      public string Name { get; set; }
        public int RowNo { get; set; }
        public int CellNo { get; set; }



    }
}

WebMvcPlusJqueryDragDropTableRows/Controllers/DragDropController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMvcPlusJqueryDragDropTableRows.Models;
using System.Data.SqlClient;
//using System.Web.Mvc;

namespace WebMvcPlusJqueryDragDropTableRows.Controllers
{
    public class DragDropController : Controller
    {

     
        
        private readonly MvcDragDropDbContext _context;

        public DragDropController(MvcDragDropDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var items0 = _context.tbMvcDragDropTableRows.ToList();
            var items = items0.OrderBy(p => p.RowNo).ToList();

            return View(items );
        }

        
        public JsonResult KaydetDragDrop(string ItemIDs)
        {
            int count = 1;

            List<int> lstItms = new List<int>();
            lstItms = ItemIDs.Split(",".ToCharArray()
                , StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();

            try
            {
                foreach (var itemID in lstItms)
                {
                    tbMvcDragDropTableRows dr = _context.tbMvcDragDropTableRows.Where(p => p.id == itemID).FirstOrDefault();
                    dr.RowNo = count;
                    _context.tbMvcDragDropTableRows.Update(dr);

                    _context.SaveChanges();

                    count++;
                }
            }
            catch (Exception ex)
            {
                var er = ex;
            }
            return new JsonResult(true);
        }




    }
}

WebMvcPlusJqueryDragDropTableRows/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebMvcPlusJqueryDragDropTableRows.Models;

namespace WebMvcPlusJqueryDragDropTableRows.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebMvcPlusJqueryDragDropTableRows/Views/DragDrop/Index.cshtml
@model IEnumerable<WebMvcPlusJqueryDragDropTableRows.Models.tbMvcDragDropTableRows>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" 
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" 
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#sortable").sortable({

        });

        @*$("#sortable").sortable({
            update: function (event, ui) {
                var ItemidS = ""
                $("#sortable").find(".taskSingleInLine").each(function () {
                    var itemId = $(this).attr("data-taskId");
                    ItemidS = ItemidS + itemId + ",";

                    console.log(ItemidS);

                    //alert('ItemidS -0 : ' + ItemidS);
                });
                //alert('ItemidS -1 : ' + ItemidS);
                $.ajax(
                    {


                        url: '@Url.Action("KaydetDragDrop","DragDrop")',
                        data: { ItemIDs : ItemidS },
                        type: 'POST',
                        success: function(data)
                        {
                            //alert('1');
                        },
                        error: function (xhr,status,error) {
                            //alert('0');
                        }
                    });

            }


        });*@

    });

    function UpdatePosition() {
       /*  $("#sortable").sortable({*/
         /*   update: function (event, ui) {*/
                var ItemidS = ""
                $("#sortable").find(".taskSingleInLine").each(function () {
                    var itemId = $(this).attr("data-taskId");
                    ItemidS = ItemidS + itemId + ",";

                    console.log(ItemidS);

                    //alert('ItemidS -0 : ' + ItemidS);
                });
                //alert('ItemidS -1 : ' + ItemidS);
                $.ajax(
                    {


                        url: '@Url.Action("KaydetDragDrop","DragDrop")',
                        data: { ItemIDs : ItemidS },
                        type: 'POST',
                        success: function(data)
                        {
                            //alert('1');
                        },
                        error: function (xhr,status,error) {
                            //alert('0');
                        }
                    });

          /*  }*/


      /*  });*/


        alert('UpdatePosition  ');
    }
</script>
<h1>Index</h1>

<p>
 
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RowNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CellNo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="sortable" style="cursor:pointer">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="taskSingleInLine" id="task@(item.id)" data-taskId="@(item.id)">
                    @Html.DisplayFor(modelItem => item.RowNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CellNo)
                </td>
                <td>
                </td>
            </tr>


        }
    </tbody>
</table>
<a class="btn btn-primary" onclick="UpdatePosition();">Kaydet</a>

WebMvcPlusJqueryDragDropTableRows/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMvcPlusJqueryDragDropTableRows/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMvcPlusJqueryDragDropTableRows</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMvcPlusJqueryDragDropTableRows</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebMvcPlusJqueryDragDropTableRows - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>